fix: (DSO-2029) Fix action script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,18 +11,17 @@ runs:
     - name: Determine if current git ref follows the convention
       shell: bash -leo pipefail {0}
       run: |
-        echo "Printing current environment variables for debugging purposes..."
-        env | grep GITHUB_
-
         CURRENT_REF=${GITHUB_REF##*/}
+        REGEX_PRODUCTION="^v([0-9]+\.[0-9]+\.[0-9]+)$"
+        REGEX_UAT="^v([0-9].[0-9].[0-9])(-uat.[0-9]{1,2})$"
 
         echo "Current git reference : ${CURRENT_REF}"
 
-        if [[ "$CURRENT_REF" =~ ^v([0-9].[0-9].[0-9])$ || "$CURRENT_REF" =~ ^v([0-9].[0-9].[0-9])(-uat.[0-9]{1,2})$]]; then
-          echo "The tag created for this deployment follows the defined conventions."
-        else
-          echo "Error:"
-          echo "The tag created for this deployment does not match defined conventions."
-          echo "Check the README's 'Releases and deployments' section for more details."
-          exit 1
+        if ! [[ $CURRENT_REF =~ $REGEX_PRODUCTION || $CURRENT_REF =~ $REGEX_UAT ]]; then
+            echo "Error:"
+            echo "The tag created for this deployment does not match defined conventions."
+            echo "Check the README's 'Releases and deployments' section for more details."
+            exit 1
         fi
+        echo "The tag created for this deployment follows the defined conventions."
+
